### ISSUE TITLE
ディスク使用率100%の状態での対応について

### ISSUE THREAD

**Issue by clementec-fuchinoue** [NIFTYCloud-C4SA/support#86]
現在Canvas S（ディスク：1G）を契約しており、Redmineをインストール、
運用を行なっています。

先日、ディスク使用率が100%となり、Redmineの挙動が不安定となった
ため、急遽Redmine（Rails）のログ「development.log」（270MB）を
「ファイル」メニューから削除したのですが、その後もディスク使用率は
下がらず、「CLI」メニューも「「500: Internal Server Error」となり、利用
出来ない状態となっております。
※ファイル削除時にエラーとなり、その後一覧からは消えています。

おそらく、ディスク使用率が100%での作業を行なったことで、システムが
更に不安定になったのだと思いますが、今後の対応についてご相談させて
ください。

相談内容は下記の通りです。
1. 現在のシステムの状況の確認。
2. 「CLI」メニューのエラー原因、および復旧方法について。
3. この不安定な状態を解決する方法について。
　　※ディスクのプランを1Gから5Gにする等。

Redmineをお客様に公開している状態で、既にファイルの添付が出来ない
状態となっており、早めの復旧を希望いたします。

以上、何卒よろしくお願いいたします。

**Comment by h-hirokawa** [comment]
C4SAをご利用いただき、誠にありがとうございます。
C4SAシステム担当の廣川です。

ご質問いただきました項目についてご回答申し上げます。

1. 現在のシステムの状況について
ご指摘の通り、ディスク使用率が100%である事により、ファイルへの書き込みが必要な各プロセスが正常に動作しなくなっている状態である
Redmine側のログを削除しても、ディスクの使用率が下がらない現象につきましては、railsのプロセスが削除された「development.log」の実体を参照し続けており、ディスク上からまだ消えていない可能性があります。
この場合、railsを立ち上げている「unicorn」のプロセスを「デーモン管理」パネルから再起動していただく事で、ファイルの実体もディスクから削除されるかと思われます。

2. 「CLI」のエラーにつきましても、キャンバス内で稼働しているプロセスですので、同様にディスクが100%になっている事が原因と思われます。
「デーモン管理」パネルから「pushterm」プロセスを再起動する事で復旧が可能ですが、事前にディスク使用率100%の状態を解消してからの実施をお勧めいたします。

3. 現象の解消についてですが、1で申し上げました通り、「unicorn」の再起動で一旦緩和されるかと思われます。
ただし、Redmineですとgemファイル系でもかなりの容量を消費している事、システムを稼働し続ければログはまた増えていく事から、安定稼働のためにはディスクのプランのアップグレードが望ましいかと思われます。

以上、ご確認をよろしくお願いいたします。
また何か問題がありましたら、こちらへのレスか、C4SA UI上の「お問い合わせ」メニューからご連絡をいただければと思います。
それでは、今後ともC4SAをよろしくお願いいたします。

**Comment by clementec-fuchinoue** [comment]
C4SA システム担当 廣川様

ご返答ありがとうございます。
「1.」のご返答にありました、railsを立ち上げている「unicorn」のプロセスを
「デーモン管理」パネルよりリスタートする方法を実施いたしました。
結果、正常にリスタートが完了し、削除したログの分、ディスクに空きが出来
ました。やはり実態を掴んだままとなっていたようです。大変失礼しました。

「2.」のCLIのエラーにつきましても、unicornのリスタート後に正常に起動が
出来ていることを確認済みです。

今後のことも考え、ディスクのプランを見直しを検討いたします。
※問合せにつきましても、ご案内ありがとうございました。

問題が解決しましたので、本件クローズとさせていただきます。
ありがとうございました。

以上、今後ともよろしくお願いいたします。
